h1. Forbidden disposable e-mail providers


* http://www.10minutemail.com
* http://www.10x9.com
* http://www.12minutemail.com
* http://www.20minutemail.com
* http://www.abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijk.com
* http://www.amilegit.com
* http://www.anonymbox.com
* http://www.beefmilk.com
* http://www.binkmail.com
* http://www.bobmail.info
* http://www.bugmenever.com
* http://www.chogmail.com
* http://www.cool.fr.nf
* http://www.courriel.fr.nf
* http://www.deagot.com
* http://www.demail.tk
* http://www.devnullmail.com
* http://www.dingbone.com
* http://www.dodgit.com
* http://www.e4ward.com
* http://www.eyepaste.com
* http://www.emailias.com
* http://www.fakemailgenerator.com
* http://www.filzmail.com
* http://www.fornow.eu
* http://www.frapmail.com
* http://www.fudgerub.com
* http://www.getonemail.com
* http://www.gishpuppy.com
* http://www.goemailgo.com
* http://www.guerrillamailblock.com
* http://www.humaility.com
* http://www.ifakemail.com
* http://www.ignoremail.com
* http://www.incognitomail.com
* http://www.yopmail.com
* http://www.yopmail.fr
* http://www.yopmail.net
* http://www.youmailr.com
* http://www.yxzx.net
* http://www.jetable.fr.nf
* http://www.jetable.org
* http://www.keepmymail.com
* http://www.kurzepost.de
* http://www.lookugly.com
* http://www.losemymail.com
* http://www.mailboxable.net
* http://www.mailbucket.org
* http://www.mailcatch.com
* http://www.maileater.com
* http://www.mailexpire.com
* http://www.mailinator.com
* http://www.mailinator.net
* http://www.mailinator.net
* http://www.mailinator2.com
* http://www.mailmoat.com
* http://www.mailnull.com
* http://www.mailscrap.com
* http://www.makemetheking.com
* http://www.mega.zik.dj
* http://www.meltmail.com
* http://www.mintemail.com
* http://www.mytempemail.com
* http://www.moncourrier.fr.nf
* http://www.monemail.fr.nf
* http://www.monmail.fr.nf
* http://www.nabuma.com
* http://www.no-spam.ws
* http://www.nobugmail.com
* http://www.nobuma.com
* http://www.nomail.xl.cx
* http://www.nospam.ze.tc
* http://www.nowmymail.com
* http://www.obobbo.com
* http://www.onewaymail.com
* http://www.phonymail.com
* http://www.putthisinyourspamdatabase.com
* http://www.rcpt.at
* http://www.safetymail.info
* http://www.sendspamhere.com
* http://www.smellfear.com
* http://www.sneakemail.com
* http://www.sofort-mail.de
* http://www.sogetthis.com
* http://www.soodonims.com
* http://www.spam.la
* http://www.spamavert.com
* http://www.spambox.us
* http://www.spambox.us
* http://www.spamcero.com
* http://www.spamevader.com
* http://www.spamex.com
* http://www.spamfree24.org
* http://www.spamgourmet.com
* http://www.spamherelots.com
* http://www.spamhereplease.com
* http://www.spamkill.info
* http://www.spammotel.com
* http://www.spamobox.com
* http://www.spamspot.com
* http://www.spamthisplease.com
* http://www.speed.1s.fr
* http://www.suremail.info
* http://www.tempail.com
* http://www.tempemail.net
* http://www.tempinbox.com
* http://www.tempomail.fr
* http://www.thisisnotmyrealemail.com
* http://www.tradermail.info
* http://www.trash-mail.at
* http://www.trash2009.com
* http://www.trashmail.at
* http://www.trashmail.me
* http://www.trashmail.net
* http://www.wegwerfmail.net
* http://www.wegwerfmail.org
* http://www.wh4f.org
* http://www.whyspam.me
* http://www.zippymail.info
* http://www.zippymail.info
* http://www.zoemail.com

Last Updated by Alien on 2010 04 23
